import type { FilePickerAcceptType } from "../api.ts";
import { FileElement, TransferFile } from "../elements/file.ts";
export declare const FileComponent: ({ ref, ...props }: FileComponent.Props) => import("react").DOMElement<{
    ref: (current: FileElement | null) => void;
    key?: import("react").Key | null | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "true" | "false") | undefined;
    enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
    hidden?: boolean | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "true" | "false") | undefined;
    style?: import("react").CSSProperties | undefined;
    tabIndex?: number | undefined;
    title?: string | undefined;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: import("react").AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    popover?: "" | "auto" | "manual" | undefined;
    popoverTargetAction?: "toggle" | "show" | "hide" | undefined;
    popoverTarget?: string | undefined;
    inert?: boolean | undefined;
    inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
    is?: string | undefined;
    exportparts?: string | undefined;
    part?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "true" | "false") | undefined;
    "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "true" | "false") | undefined;
    "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "true" | "false") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "true" | "false") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "true" | "false") | undefined;
    "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
    "aria-hidden"?: (boolean | "true" | "false") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "true" | "false") | undefined;
    "aria-multiline"?: (boolean | "true" | "false") | undefined;
    "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
    "aria-readonly"?: (boolean | "true" | "false") | undefined;
    "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "true" | "false") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "true" | "false") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: import("react").ReactNode | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<FileElement> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<FileElement> | undefined;
    onCut?: import("react").ClipboardEventHandler<FileElement> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<FileElement> | undefined;
    onPaste?: import("react").ClipboardEventHandler<FileElement> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<FileElement> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<FileElement> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<FileElement> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<FileElement> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<FileElement> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<FileElement> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<FileElement> | undefined;
    onFocus?: import("react").FocusEventHandler<FileElement> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<FileElement> | undefined;
    onBlur?: import("react").FocusEventHandler<FileElement> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<FileElement> | undefined;
    onChange?: import("react").FormEventHandler<FileElement> | undefined;
    onChangeCapture?: import("react").FormEventHandler<FileElement> | undefined;
    onBeforeInput?: import("react").FormEventHandler<FileElement> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<FileElement> | undefined;
    onInput?: import("react").FormEventHandler<FileElement> | undefined;
    onInputCapture?: import("react").FormEventHandler<FileElement> | undefined;
    onReset?: import("react").FormEventHandler<FileElement> | undefined;
    onResetCapture?: import("react").FormEventHandler<FileElement> | undefined;
    onSubmit?: import("react").FormEventHandler<FileElement> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<FileElement> | undefined;
    onInvalid?: import("react").FormEventHandler<FileElement> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<FileElement> | undefined;
    onLoad?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onError?: import("react").ReactEventHandler<FileElement> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<FileElement> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<FileElement> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<FileElement> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<FileElement> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<FileElement> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<FileElement> | undefined;
    onAbort?: import("react").ReactEventHandler<FileElement> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onCanPlay?: import("react").ReactEventHandler<FileElement> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<FileElement> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onDurationChange?: import("react").ReactEventHandler<FileElement> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onEmptied?: import("react").ReactEventHandler<FileElement> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onEncrypted?: import("react").ReactEventHandler<FileElement> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onEnded?: import("react").ReactEventHandler<FileElement> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadedData?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadStart?: import("react").ReactEventHandler<FileElement> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onPause?: import("react").ReactEventHandler<FileElement> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onPlay?: import("react").ReactEventHandler<FileElement> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onPlaying?: import("react").ReactEventHandler<FileElement> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onProgress?: import("react").ReactEventHandler<FileElement> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onRateChange?: import("react").ReactEventHandler<FileElement> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onResize?: import("react").ReactEventHandler<FileElement> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onSeeked?: import("react").ReactEventHandler<FileElement> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onSeeking?: import("react").ReactEventHandler<FileElement> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onStalled?: import("react").ReactEventHandler<FileElement> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onSuspend?: import("react").ReactEventHandler<FileElement> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<FileElement> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<FileElement> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onWaiting?: import("react").ReactEventHandler<FileElement> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onAuxClick?: import("react").MouseEventHandler<FileElement> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onClick?: import("react").MouseEventHandler<FileElement> | undefined;
    onClickCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onContextMenu?: import("react").MouseEventHandler<FileElement> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<FileElement> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onDrag?: import("react").DragEventHandler<FileElement> | undefined;
    onDragCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDragEnd?: import("react").DragEventHandler<FileElement> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDragEnter?: import("react").DragEventHandler<FileElement> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDragExit?: import("react").DragEventHandler<FileElement> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDragLeave?: import("react").DragEventHandler<FileElement> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDragOver?: import("react").DragEventHandler<FileElement> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDragStart?: import("react").DragEventHandler<FileElement> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onDrop?: import("react").DragEventHandler<FileElement> | undefined;
    onDropCapture?: import("react").DragEventHandler<FileElement> | undefined;
    onMouseDown?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseEnter?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseLeave?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseMove?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseOut?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseOver?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseUp?: import("react").MouseEventHandler<FileElement> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<FileElement> | undefined;
    onSelect?: import("react").ReactEventHandler<FileElement> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<FileElement> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchMove?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchStart?: import("react").TouchEventHandler<FileElement> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<FileElement> | undefined;
    onPointerDown?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerMove?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerUp?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerOver?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerOut?: import("react").PointerEventHandler<FileElement> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<FileElement> | undefined;
    onScroll?: import("react").UIEventHandler<FileElement> | undefined;
    onScrollCapture?: import("react").UIEventHandler<FileElement> | undefined;
    onScrollEnd?: import("react").UIEventHandler<FileElement> | undefined;
    onScrollEndCapture?: import("react").UIEventHandler<FileElement> | undefined;
    onWheel?: import("react").WheelEventHandler<FileElement> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<FileElement> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<FileElement> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<FileElement> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<FileElement> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<FileElement> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<FileElement> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<FileElement> | undefined;
    onToggle?: import("react").ToggleEventHandler<FileElement> | undefined;
    onBeforeToggle?: import("react").ToggleEventHandler<FileElement> | undefined;
    onTransitionCancel?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionCancelCapture?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionRun?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionRunCapture?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionStart?: import("react").TransitionEventHandler<FileElement> | undefined;
    onTransitionStartCapture?: import("react").TransitionEventHandler<FileElement> | undefined;
    maxSize?: number;
    multiple?: boolean;
    types?: FilePickerAcceptType[];
}, FileElement>;
export declare namespace FileComponent {
    type Element = FileElement;
    interface Props extends React.ComponentProps<"a-file"> {
    }
}
export { TransferFile };
declare global {
    interface HTMLElementTagNameMap {
        "a-file": FileElement;
    }
}
declare module "react" {
    namespace JSX {
        interface IntrinsicElements {
            "a-file": React.DetailedHTMLProps<React.HTMLAttributes<FileElement> & {
                maxSize?: number;
                multiple?: boolean;
                types?: FilePickerAcceptType[];
            }, FileElement>;
        }
    }
}
